

# Proofs are not very future proof because there aren't good packaging
# systems for them.

# Still, we can use containers and other tricks to make a given proof
# build reliably.

.PHONY: tools 

#-------------------------------------------------------------------

ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

AGDA24=$(ROOT_DIR)/bin/agda24/agda
# Here's an alternate command to run Agda 2.4.2.3:
# AGDA= docker run -i --rm -v $(HOME):$(HOME) banacorn/agda:2.4.2.3 agda

AGDA25=$(ROOT_DIR)/bin/agda25/agda

# GHC=ghc
GHC= stack --resolver=lts-6.1 ghc --

#-------------------------------------------------------------------

tools: $(AGDA24) $(AGDA25)

# Install agda 2.4.2.3
build-agda24: $(AGDA24)
$(AGDA24):
	mkdir -p $(shell dirname $(AGDA24))
	stack install --local-bin-path=./bin/agda24 --resolver=lts-3.0 Agda

build-agda25: $(AGDA25)
$(AGDA25):
	mkdir -p $(shell dirname $(AGDA25))
	stack install --local-bin-path=./bin/agda25/ --resolver=lts-6.1 Agda

# NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/16.03.tar.gz
NIX_PATH=nixpkgs=https://nixos.org/releases/nixpkgs/nixpkgs-16.09pre83147.df89584/nixexprs.tar.xz

# With 16.09pre:
build-coq:
	NIX_PATH=$(NIX_PATH) nix-env -i coq-8.5pl1

build-isabelle:
	NIX_PATH=$(NIX_PATH) nix-env -i isabelle-2016

