

# Proofs are not very future proof because there aren't good packaging
# systems for them.

# Still, we can use containers and other tricks to make a given proof
# build reliably.

.PHONY: tools 

#-------------------------------------------------------------------

ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

AGDA=$(ROOT_DIR)/bin/agda
# Here's an alternate command to run Agda 2.4.2.3:
# AGDA= docker run -i --rm -v $(HOME):$(HOME) banacorn/agda:2.4.2.3 agda

AGDA25=$(ROOT_DIR)/bin/agda25/agda

#-------------------------------------------------------------------

tools: $(AGDA) $(AGDA25)

# Install agda 2.4.2.3
build-agda24: $(AGDA)
$(AGDA):
	stack install --local-bin-path=./bin --resolver=lts-3.0 Agda

build-agda25: $(AGDA25)
$(AGDA25):
	mkdir -p ./bin/agda25/
	stack install --local-bin-path=./bin/agda25/ --resolver=lts-6.1 Agda

# NIX_PATH=

# With 16.09pre:
build-coq:
	nix-env -i coq-8.5pl1

build-isabelle:
	nix-env -i isabelle-2016
